# Generated by Django 6.1 on 2026-09-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='Noticias')),
                ('data', models.DateField(auto_now_add=True)),
                ('conteudo', models.TextField()),
            ],
        ),
    ]
