# Generated by Django 6.1 on 2026-09-14 11:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Conteúdo'),
        ),
    ]
