# Generated by Django 6.1 on 2026-09-26 14:07

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_criar_grupos_de_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApresentacaoNapne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Conheça o NAPNE', max_length=200)),
                ('conteudo', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Conteúdo')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemCarrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='apresentacao_napne')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.apresentacaonapne')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
