# Generated by Django 6.1 on 2026-09-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feedbackprivado_feedbackpublico'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackprivado',
            name='editado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackpublico',
            name='editado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackprivado',
            name='conteudo',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feedbackpublico',
            name='conteudo',
            field=models.TextField(max_length=500),
        ),
    ]
