# Generated by Django 6.1 on 2026-09-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedbackprivado_editado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackprivado',
            name='editado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackpublico',
            name='editado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
