# Generated by Django 6.1 on 2026-09-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pei'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pei',
            old_name='data',
            new_name='data_envio',
        ),
    ]
