# Generated by Django 6.1 on 2026-09-24 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_data_pei_data_envio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoNapne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_napne_avaliadas', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_napne', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
