# Generated by Django 6.1 on 2026-09-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apresentacaonapne_imagemcarrossel'),
        ('core', '0005_alter_feedbackprivado_editado_em_and_more'),
    ]

    operations = [
    ]
