# Generated by Django 6.1 on 2026-10-04 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260927_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('destino_tipo', models.CharField(choices=[('todos', 'Todos os usuários'), ('professores', 'Todos os professores'), ('alunos', 'Todos os alunos'), ('napne', 'Todos os membros do NAPNE'), ('usuario', 'Um usuário específico')], default='todos', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('lida_por', models.ManyToManyField(blank=True, related_name='notificacoes_lidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
